# Generated by Django 5.1.15 on 2026-09-28 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='references/%Y/%m/')),
                ('text_content', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('guidelines', 'Writing Guidelines'), ('screenplay_rules', 'Screenplay Structure'), ('storytelling', 'Storytelling Principles'), ('blog_standards', 'Blog Guidelines'), ('formatting', 'Formatting Examples'), ('user_custom', 'User Provided Reference')], default='user_custom', max_length=50)),
                ('is_global', models.BooleanField(default=False, help_text='Global reference accessible to all users')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('qdrant_point_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='references.writingreference')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='writingreference',
            index=models.Index(fields=['user', '-created_at'], name='references__user_id_184b52_idx'),
        ),
        migrations.AddIndex(
            model_name='writingreference',
            index=models.Index(fields=['is_global', 'status'], name='references__is_glob_afffbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='referencechunk',
            unique_together={('reference', 'chunk_index')},
        ),
    ]
