# Generated by Django 5.1.15 on 2026-09-28 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Document', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('ai_result', models.TextField(blank=True, default='')),
                ('mode', models.CharField(choices=[('blog', 'Blog'), ('article', 'Article'), ('story', 'Story'), ('movie_web_series', 'Movie / Web Series'), ('screenplay', 'Screenplay Draft'), ('custom', 'Custom')], default='blog', max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Hinglish', 'Hinglish')], default='English', max_length=50)),
                ('tone', models.CharField(choices=[('Simple', 'Simple'), ('Professional', 'Professional'), ('Friendly', 'Friendly'), ('Creative', 'Creative'), ('Formal', 'Formal'), ('Casual', 'Casual'), ('Cinematic', 'Cinematic'), ('Emotional', 'Emotional'), ('Technical', 'Technical')], default='Simple', max_length=50)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('ai_result', models.TextField(blank=True, default='')),
                ('change_summary', models.CharField(default='Saved version', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-updated_at'], name='documents_d_user_id_4b7c15_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'mode'], name='documents_d_user_id_6bda81_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'language'], name='documents_d_user_id_559559_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-version_number'], name='documents_d_documen_654958_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
